title: Rizki Rizki
email: rizki@rizkidoank.com
description: >-
  Rizki personal blog, contains everything that
  I want to share. I hope the contents good for you.
baseurl: ""
url: "https://rizkidoank.com"
github_username:  rizkidoank
timezone: Asia/Jakarta
permalink: pretty

markdown: kramdown
theme: minima
show_excerpts: false
google_analytics: UA-78100671-2
plugins:
  - jekyll-seo-tag
  - jekyll-feed

disqus:
    shortname: rizkidoank

facebook_username: rtechlab
instagram_username: rizkidoank
linkedin_username: rizkidoank
telegram_username: rizkidoank
rss: rss

exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
