baseURL: https://rizkidoank.com
title: rizkidoank

theme: ananke

paginate: 10

enableRobotsTXT: true

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

googleAnalytics: "UA-78100671-2"
disqusShortname: "rizkidoank"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: rizkidoank
  description: 'Blog rizkidoank'
  author: Me
  show_reading_time: true
  
  github: 'https://github.com/rizkidoank'
  facebook: 'https://facebook.com/rizkidoank.dev/'
  instagram: 'https://instagram.com/rizkidoank'
  linkedin: 'https://linkedin.com/in/rizkidoank'

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 10

permalinks:
  posts: /:year/:month/:day/:title"

# DefaultContentLanguage: en
# languages:
#   en:
#     languageName: English
#     weight: 1
#   id:
#     languageName: Indonesian
#     weight: 2
#     description: Blog rizkidoank
