baseURL: https://rizkidoank.com
title: rizkidoank
pagination:
  pagerSize: 5
module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod
enableEmoji: true
enableRobotsTXT: true

params:
  homeInfoParams:
    Title: "Halo \U0001F44B"
    Content: Welcome to my blog! I'm a Cloud Infrastructure engineer that has interest on ML / AI Infrastructure. 
  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/rizkidoank/"
    - name: github
      url: "https://github.com/rizkidoank"
    - name: gitlab
      url: "https://gitlab.com/rizkidoank"
  env: production
  title: rizkidoank
  description: "rizkidoank's blog"
  keywords:
  - blog
  - portfolio
  author: Me
  defaultTheme: dark
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  assets:
    disableHLJS: false
    disableFingerprinting: false
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"
  profileMode:
    enabled: true
    title: rizkidoank
    subtitle: Welcome to my personal blog 😁
    imageUrl: https://1.gravatar.com/avatar/e5e8126a6d7ce5ed460f301c94af0c1267c53734c27d09e07b71cad310ee1016?size=256
    imageWidth: 256
    imageHeight: 256
    imageTitle: rizkidoank
    buttons:
      - name: Posts
        url: posts
      - name: Search
        url: /search
      - name: Tags
        url: tags
menu:
  main:
    - identifier: posts
      name: Posts
      url: posts
      weight: 10
    - identifier: jajananku
      name: Jajananku
      url: jajananku
      weight: 30
    - identifier: tags
      name: Tags
      url: tags
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

services:
  googleAnalytics:
    ID: G-11PHT87RFD
  disqus:
    shortname: rizkidoank

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: /:year/:month/:day/:title"

outputs:
  home:
  - HTML
  - RSS
  - JSON

DefaultContentLanguage: en
languages:
  en:
    languageCode: en-US
    languageName: English
    weight: 1

